# Generated by Django 5.1.3 on 2025-02-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_sell_additional_image1_sell_additional_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='property_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
