# Generated by Django 5.1.3 on 2025-02-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_sell_property_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='property_history',
        ),
    ]
