# Generated by Django 5.1.3 on 2025-02-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_sell_house_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('villa', 'Villa'), ('apartment', 'Apartment'), ('land', 'Land')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='properties/')),
            ],
        ),
        migrations.AlterField(
            model_name='sell',
            name='house_type',
            field=models.CharField(choices=[('single_family', 'Single Family House'), ('villa', 'Villa'), ('farmhouse', 'Farmhouse'), ('land', 'Land'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('bungalow', 'Bungalow'), ('duplex', 'Duplex'), ('penthouse', 'Penthouse'), ('studio', 'Studio'), ('cottage', 'Cottage'), ('mansion', 'Mansion')], max_length=50),
        ),
    ]
