# Generated by Django 5.1.3 on 2025-02-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_property_alter_sell_house_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
