# Generated by Django 5.1.3 on 2025-02-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sell_bathrooms_sell_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='description',
            field=models.CharField(max_length=1255),
        ),
    ]
