# Generated by Django 5.1.3 on 2025-02-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_sell_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='additional_image1',
            field=models.ImageField(blank=True, null=True, upload_to='houses/other_images/'),
        ),
        migrations.AddField(
            model_name='sell',
            name='additional_image2',
            field=models.ImageField(blank=True, null=True, upload_to='houses/other_images/'),
        ),
        migrations.AddField(
            model_name='sell',
            name='bathroom_image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/other_images/'),
        ),
        migrations.AddField(
            model_name='sell',
            name='bedroom_image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/other_images/'),
        ),
        migrations.AddField(
            model_name='sell',
            name='kitchen_image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/other_images/'),
        ),
        migrations.AddField(
            model_name='sell',
            name='livingroom_image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/other_images/'),
        ),
        migrations.AddField(
            model_name='sell',
            name='outside_image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/other_images/'),
        ),
        migrations.AddField(
            model_name='sell',
            name='square_feet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='description',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
    ]
