# Generated by Django 5.1.3 on 2025-02-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_sell_property_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='property_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
