# Generated by Django 5.1.3 on 2025-02-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_sell_property_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyhistory',
            name='house',
        ),
        migrations.DeleteModel(
            name='HouseImage',
        ),
        migrations.DeleteModel(
            name='PropertyHistory',
        ),
    ]
