# Generated by Django 5.1.3 on 2025-02-10 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_sell_built_year_sell_ending_year_sell_starting_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='ending_year',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='starting_year',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='usage_history',
        ),
        migrations.CreateModel(
            name='PropertyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='User Name')),
                ('starting_year', models.IntegerField(verbose_name='Starting Year')),
                ('ending_year', models.IntegerField(verbose_name='Ending Year')),
                ('price', models.IntegerField(verbose_name='Price Paid')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='myapp.sell')),
            ],
        ),
    ]
