# Generated by Django 5.1.6 on 2025-02-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_property'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saved',
            unique_together={('user', 'house')},
        ),
    ]
