# Generated by Django 5.1.6 on 2025-02-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_agent_listing_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='listing',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
